name: combine_conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - git
  - pip:
    - pydantic
    - numpy==1.26.4
    - pandas
    - scikit-image
    - dask
    - dask-image
    - psutil
    - numba
    - tqdm
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git